config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  resources :merchants, only: %i[index edit update]

  namespace :api do
    namespace :v1 do
      post :login, to: 'authentication#login'

      resource :payments, only: :create
    end
  end

  root to: 'merchants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorize_transaction.rb
class AuthorizeTransaction < Transaction
  validates :amount, presence: true

  # gem stateful_enum doesn't work properly
  # in case of defining in parent class
  include HasStateMachine
end

app/models/charge_transaction.rb
class ChargeTransaction < Transaction
  validates :amount, presence: true

  # gem stateful_enum doesn't work properly
  # in case of defining in parent class
  include HasStateMachine
end

app/models/concerns/has_state_machine.rb
require 'active_support/concern'

module HasStateMachine
  extend ActiveSupport::Concern

  included do
    enum status: { initial: 0, approved: 1, reversed: 2, refunded: 3, error: 4 } do
      event :approve do
        transition initial: :approved
      end

      event :refund do
        transition approved: :refunded
      end

      event :reverse do
        transition initial: :reversed
      end

      event :mark_as_error do
        transition all => :error
      end
    end
  end
end

app/models/refund_transaction.rb
class RefundTransaction < Transaction
  validates :amount, presence: true

  # gem stateful_enum doesn't work properly
  # in case of defining in parent class
  include HasStateMachine
end

app/models/reversal_transaction.rb
class ReversalTransaction < Transaction
  # gem stateful_enum doesn't work properly
  # in case of defining in parent class
  include HasStateMachine
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :merchant, class_name: :User, foreign_key: :uuid

  validates :customer_phone, presence: true
  validate :check_positive_amount, :check_active_merchant

  private

  def check_positive_amount
    return if amount.nil?

    if amount.negative?
      errors.add(:amount, "can't be negative")
    elsif amount.zero?
      errors.add(:amount, "can't be zero")
    end
  end

  def check_active_merchant
    errors.add(:merchant, 'inactive merchant') unless merchant.active?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  enum role: { admin: 0, merchant: 1 }

  validates :role, :total_transaction_sum, presence: true
  validate :check_total_transaction_sum_is_positive

  scope :merchants, -> { where role: :merchant }
  scope :admins, -> { where role: :admin }

  has_many :transactions, foreign_key: :uuid, dependent: :restrict_with_error

  protected

  def password_required?
    return false if merchant?

    super
  end

  def check_total_transaction_sum_is_positive
    errors.add(:total_transaction_sum, "can't be negative") if total_transaction_sum.negative?
  end
end

app/controllers/api/v1/authentication_controller.rb
module Api
  module V1
    class AuthenticationController < BaseController
      before_action :authorize_request, except: :login

      TOKEN_LIFETIME = 7.days.freeze

      # POST /auth/login
      def login
        user = User.admins.find_by_email(params[:email])
        customer_params = params[:customer]
        if user&.valid_password?(params[:password])
          time = (Time.zone.now + TOKEN_LIFETIME).to_i
          token = JsonWebToken.encode(customer_params, time)
          render json: { token: token, exp: time }, status: :ok
        else
          render json: { error: 'unauthorized' }, status: :unauthorized
        end
      end

      private

      def login_params
        params.permit(:email, :password).require(:customer).permit(:email, :phone)
      end
    end
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :setup_headers

      protected

      def setup_headers
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
        headers['Access-Control-Request-Method'] = '*'
        headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
      end

      def authorize_request
        header = request.headers['Authorization']
        header = header.split(' ').last if header
        begin
          @current_customer = JsonWebToken.decode(header)
        rescue JWT::DecodeError => e
          render json: { errors: e.message }, status: :unauthorized
        end
      end
    end
  end
end

app/controllers/api/v1/payments_controller.rb
module Api
  module V1
    class PaymentsController < BaseController
      before_action :authorize_request

      def create
        transaction_attributes = {
          amount: permitted_params[:amount], customer_phone: current_customer[:phone],
          customer_email: current_customer[:email], uuid: permitted_params[:uuid]
        }
        response = Accountant.new(
          permitted_params[:type], transaction_attributes
        ).call
        status = response.key?(:errors) ? :not_acceptable : :ok
        render json: response, status: status
      end

      private

      attr_reader :current_customer

      def permitted_params
        @permitted_params ||= params.permit(:amount, :type, :uuid)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @merchants = LoadMerchants.call(params)
  end

  def edit
    @merchant = LoadMerchant.call(params)
    @transactions = LoadTransactions.call(params)
  end

  def update
    @merchant = LoadMerchant.call(params)
    if @merchant.update resource_params
      redirect_to action: :index
    else
      render :edit
    end
  end

  private

  def authenticate_admin!
    redirect_to user_session_path unless current_user.admin?
  end

  def resource_params
    params.require(:user).permit(:email, :name, :id, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .container.mt-3
      header
        .text-left
          = link_to "Info", "https://github.com/lxkuz/forum"
        - if current_user
          .text-right
            = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-sml btn-danger'
      == yield

app/views/merchants/edit.html.slim
.row
  .col-md-4
    h3 = "Edit merchant"
    h4 = "Balance: #{number_to_currency(@merchant.total_transaction_sum)}"
    = form_with(model: @merchant, url: merchant_url(@merchant)) do |f|
      .form-inputs
        .label
          'Name
        = f.text_field :name, class: "form-control"
        .label
          'Email
        = f.text_field :email, class: "form-control"
        .label
          'Active      
        = f.check_box :active, class: "form-control"
      .form-actions
        .btn
          = f.submit "Submit", class: 'btn btn-success'
        .btn
          = link_to 'Back', merchants_url, class: 'btn btn-primary'
  .col-md-4
    h3 = "Transactions"
    table.table.table-striped.table-bordered
      thead
        tr
          td= 'ID'
          td= 'Customer email'
          td= 'Customer phone'
          td= 'Amount'
          td= 'Type'
          td= 'Status'
          td= 'Created at'
      tbody
        - @transactions.each do |transaction_record|
          - transaction = TransactionPresenter.new(transaction_record)
          tr
            td= transaction.id
            td= transaction.customer_email
            td= transaction.customer_phone
            td= transaction.amount
            td= transaction.type
            td= transaction.status
            td= transaction.created_at

app/views/merchants/index.html.slim
h3.text-center= 'Merchants'
table.table.table-striped.table-bordered
  thead
    tr
      td ID
      td Name
      td Email
      td Active
      td
  tbody
    - @merchants.each do |merchant_data|
      - merchant = MerchantPresenter.new(merchant_data)
      tr
        td= merchant.id
        td= merchant.name
        td= merchant.email
        td= merchant.active
        td
          = link_to "Edit", url_for(action: :edit, controller: params[:controller], id: merchant.id), class: 'btn btn-sml btn-success'
.text-center
  == paginate @merchants